GET http://localhost:3000/currencies/
###
GET http://localhost:3000/currencies/5edb98d0ec71770918ea8302

###
POST http://localhost:3000/currencies/
Content-Type: application/json

{   "name":"USD",
    "arabicName":"الدولار المريكي",
    "sellPrice":"137",
    "buyPrice":"138"
}

###

DELETE  http://localhost:3000/currencies/5ecbb2a54e7f37235cf8fa7c


###

PATCH   http://localhost:3000/currencies/5edb98d0ec71770918ea8302
Content-Type: application/json

{
    "buyPrice":"130"
}
